spring.application.name=garra
spring.datasource.url=jdbc:postgresql://localhost/garra
spring.datasource.username=postgres
spring.datasource.password=0420Melo@
spring.security.user.name=root
spring.security.user.password=04200420
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG