spring.application.name=garra
spring.datasource.url=jdbc:postgresql://localhost/garra
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.web.error.include-stacktrace=never
api.security.token=${JWT_TOKEN_PASS}